[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.18'
optimizer = true
optimizer_runs = 1000
# via_ir = true

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
